name: my_dbt_project
version: 1.0
config-version: 2

profile: default

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["seed"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  my_dbt_project:
    staging:
      materialized: view
    marts:
      materialized: table
